# Generated by Django 3.2.13 on 2022-04-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='bike',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
