# Generated by Django 3.2.13 on 2022-04-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_auto_20220430_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
