# Generated by Django 3.2.13 on 2022-05-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_alter_bike_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='serial',
            new_name='group_no',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='part',
            name='item_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='part_group',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='part',
            name='part_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
