# Generated by Django 3.2.13 on 2022-05-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_auto_20220502_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_relevant',
            field=models.BooleanField(default=False),
        ),
    ]
