# Generated by Django 3.2.13 on 2022-05-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_part_is_relevant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
