# Generated by Django 3.2.13 on 2022-05-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_alter_part_bike_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
