# Generated by Django 3.2.13 on 2022-05-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_alter_part_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
