# Generated by Django 3.2.13 on 2022-05-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0013_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
