# Generated by Django 3.2.13 on 2022-05-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0014_alter_current_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='is_relevant',
        ),
    ]
