# Generated by Django 3.2.13 on 2022-05-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0015_remove_part_is_relevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='trackable',
            field=models.BooleanField(default=False),
        ),
    ]
