# Generated by Django 3.2.13 on 2022-06-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0016_part_trackable'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='used_last_time',
            field=models.IntegerField(default=0),
        ),
    ]
