# Generated by Django 3.2.13 on 2022-06-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0017_part_used_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='quantity',
            field=models.IntegerField(default=100),
        ),
    ]
