# Generated by Django 3.2.13 on 2022-06-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0018_alter_part_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
