# Generated by Django 3.2.13 on 2022-06-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0019_alter_part_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelsheet',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
