# Generated by Django 3.2.13 on 2022-06-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0020_excelsheet_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='in_excelsis',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
