# Generated by Django 3.2.13 on 2022-06-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0021_part_in_excelsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='threshold',
            field=models.IntegerField(default=0),
        ),
    ]
