# Generated by Django 3.2.14 on 2023-02-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0023_remove_part_trackable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='in_excelsis',
        ),
        migrations.RemoveField(
            model_name='part',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='part',
            name='threshold',
        ),
        migrations.RemoveField(
            model_name='part',
            name='used_last_time',
        ),
    ]
