# Generated by Django 3.2.14 on 2023-02-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0024_auto_20230228_0554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Current',
        ),
        migrations.RemoveField(
            model_name='part',
            name='bike',
        ),
        migrations.DeleteModel(
            name='Bike',
        ),
    ]
