# Generated by Django 3.2.14 on 2023-02-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0026_part_out_of_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
