# Generated by Django 3.2.14 on 2023-02-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0027_part_expected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='danish_slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
