# Generated by Django 3.2.13 on 2023-03-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0028_part_danish_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
