# Generated by Django 4.2 on 2023-04-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0029_part_inactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='bike_models',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
