# Generated by Django 4.0.5 on 2023-02-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='json_data',
            field=models.JSONField(default=list),
        ),
    ]
