# Generated by Django 3.2.14 on 2023-02-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_order',
            field=models.BooleanField(default=True),
        ),
    ]
